language: elixir
elixir:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 21.0

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
